sudo: required

language: node_js

install: true

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t jchancehud/cidbadged:latest
  - docker push jchancehud/cidbadged:latest
